error 3
Using standard pip install.

Collecting streamlit==1.46.0 (from -r /mount/src/edufruits_v3/streamlit/requirements.txt (line 1))

  Downloading streamlit-1.46.0-py3-none-any.whl.metadata (9.0 kB)

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5

ERROR: Could not find a version that satisfies the requirement tensorflow==2.15.0 (from versions: none)

ERROR: No matching distribution found for tensorflow==2.15.0

[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip

Checking if Streamlit is installed

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/exec_code.py:128 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/script_runner.py:669 in code_to_exec

  /mount/src/edufruits_v3/streamlit/app.py:9 in <module>

      6 """

      7

      8 import streamlit as st

  ❱   9 import tensorflow as tf

     10 from tensorflow.keras.models import load_model

     11 import numpy as np

     12 import matplotlib.pyplot as plt

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'tensorflow'

Found Streamlit version 1.46.1 in the environment

Installing rich for an improved exception logging

Using standard pip install.

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/exec_code.py:128 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/script_runner.py:669 in code_to_exec

  /mount/src/edufruits_v3/streamlit/app.py:9 in <module>

      6 """

      7

      8 import streamlit as st

  ❱   9 import tensorflow as tf

     10 from tensorflow.keras.models import load_model

     11 import numpy as np

     12 import matplotlib.pyplot as plt

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'tensorflow'

2025-06-27 20:19:53.751 503 GET /script-health-check (127.0.0.1) 101.87ms

Collecting rich>=10.14.0

  Downloading rich-14.0.0-py3-none-any.whl.metadata (18 kB)

Collecting markdown-it-py>=2.2.0 (from rich>=10.14.0)

  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)

Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.14.0)

  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)

Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.14.0)

  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)

Downloading rich-14.0.0-py3-none-any.whl (243 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 12.6 MB/s eta 0:00:00[2025-06-27 20:19:54.126228]

Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 120.1 MB/s eta 0:00:00[2025-06-27 20:19:54.140197]

Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 82.9 MB/s eta 0:00:00[2025-06-27 20:19:54.169369]

Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)

Installing collected packages: pygments, mdurl, markdown-it-py, rich

  Attempting uninstall: pygments

    Found existing installation: Pygments 2.19.2

    Uninstalling Pygments-2.19.2:

      Successfully uninstalled Pygments-2.19.2

  Attempting uninstall: mdurl

    Found existing installation: mdurl 0.1.2

    Uninstalling mdurl-0.1.2:

      Successfully uninstalled mdurl-0.1.2

  Attempting uninstall: markdown-it-py

    Found existing installation: markdown-it-py 3.0.0

    Uninstalling markdown-it-py-3.0.0:

      Successfully uninstalled markdown-it-py-3.0.0

  Attempting uninstall: rich

    Found existing installation: rich 14.0.0

    Uninstalling rich-14.0.0:

      Successfully uninstalled rich-14.0.0

Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygments-2.19.2 rich-14.0.0

[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip

────────────────────────────────────────────────────────────────────────────────────────

[20:19:57] ❗️ installer returned a non-zero exit code

[20:22:08] 🐙 Pulling code changes from Github...

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/exec_code.py:128 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/script_runner.py:669 in code_to_exec

  /mount/src/edufruits_v3/streamlit/app.py:9 in <module>

      6 """

      7

      8 import streamlit as st

  ❱   9 import tensorflow as tf

     10 from tensorflow.keras.models import load_model

     11 import numpy as np

     12 import matplotlib.pyplot as plt

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'tensorflow'

[20:22:08] ❗️

2025-06-27 20:22:08.946 503 GET /script-health-check (127.0.0.1) 108.13ms

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/exec_code.py:128 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/script_runner.py:669 in code_to_exec

  /mount/src/edufruits_v3/streamlit/app.py:9 in <module>

      6 """

      7

      8 import streamlit as st

  ❱   9 import tensorflow as tf

     10 from tensorflow.keras.models import load_model

     11 import numpy as np

     12 import matplotlib.pyplot as plt

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'tensorflow'

[20:22:12] 📦 Processing dependencies...

──────────────────────────────────────── uv ───────────────────────────────────────────

Using uv pip install.

Using Python 3.13.5 environment at /home/adminuser/venv

  × No solution found when resolving dependencies:

  ╰─▶ Because tensorflow==2.17.0 has no wheels with a matching Python ABI

      tag and you require tensorflow==2.17.0, we can conclude that your

      requirements are unsatisfiable.

Checking if Streamlit is installed

Found Streamlit version 1.46.1 in the environment

Installing rich for an improved exception logging

Using uv pip install.

Using Python 3.13.5 environment at /home/adminuser/venv

Audited 1 package in 2ms

────────────────────────────────────────────────────────────────────────────────────────

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/exec_code.py:128 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/script_runner.py:669 in code_to_exec

  /mount/src/edufruits_v3/streamlit/app.py:9 in <module>

      6 """

      7

      8 import streamlit as st

  ❱   9 import tensorflow as tf

     10 from tensorflow.keras.models import load_model

     11 import numpy as np

     12 import matplotlib.pyplot as plt

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'tensorflow'

2025-06-27 20:22:14.004 503 GET /script-health-check (127.0.0.1) 128.13ms

──────────────────────────────────────── pip ───────────────────────────────────────────

Using standard pip install.

Collecting streamlit==1.46.0 (from -r /mount/src/edufruits_v3/streamlit/requirements.txt (line 1))

  Downloading streamlit-1.46.0-py3-none-any.whl.metadata (9.0 kB)

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5

ERROR: Could not find a version that satisfies the requirement tensorflow==2.17.0 (from versions: none)

ERROR: No matching distribution found for tensorflow==2.17.0

[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip

Checking if Streamlit is installed

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/exec_code.py:128 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/script_runner.py:669 in code_to_exec

  /mount/src/edufruits_v3/streamlit/app.py:9 in <module>

      6 """

      7

      8 import streamlit as st

  ❱   9 import tensorflow as tf

     10 from tensorflow.keras.models import load_model

     11 import numpy as np

     12 import matplotlib.pyplot as plt

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'tensorflow'

Found Streamlit version 1.46.1 in the environment

Installing rich for an improved exception logging

Using standard pip install.

Collecting rich>=10.14.0

  Downloading rich-14.0.0-py3-none-any.whl.metadata (18 kB)

Collecting markdown-it-py>=2.2.0 (from rich>=10.14.0)

  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)

Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.14.0)

  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)

Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.14.0)

  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)

Downloading rich-14.0.0-py3-none-any.whl (243 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 11.9 MB/s eta 0:00:00[2025-06-27 20:22:17.443206]

Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 120.9 MB/s eta 0:00:00[2025-06-27 20:22:17.457807]

Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 52.9 MB/s eta 0:00:00[2025-06-27 20:22:17.495198]

Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)

Installing collected packages: pygments, mdurl, markdown-it-py, rich

  Attempting uninstall: pygments

    Found existing installation: Pygments 2.19.2

    Uninstalling Pygments-2.19.2:

      Successfully uninstalled Pygments-2.19.2

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/exec_code.py:128 in exec_func_with_error_handling

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru

  nner/script_runner.py:669 in code_to_exec

  /mount/src/edufruits_v3/streamlit/app.py:9 in <module>

      6 """

      7

      8 import streamlit as st

  ❱   9 import tensorflow as tf

     10 from tensorflow.keras.models import load_model

     11 import numpy as np

     12 import matplotlib.pyplot as plt

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'tensorflow'

2025-06-27 20:22:18.955 503 GET /script-health-check (127.0.0.1) 127.56ms

  Attempting uninstall: mdurl

    Found existing installation: mdurl 0.1.2

    Uninstalling mdurl-0.1.2:

      Successfully uninstalled mdurl-0.1.2

  Attempting uninstall: markdown-it-py

    Found existing installation: markdown-it-py 3.0.0

    Uninstalling markdown-it-py-3.0.0:

      Successfully uninstalled markdown-it-py-3.0.0

  Attempting uninstall: rich

    Found existing installation: rich 14.0.0

    Uninstalling rich-14.0.0:

      Successfully uninstalled rich-14.0.0

Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygments-2.19.2 rich-14.0.0

[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip

────────────────────────────────────────────────────────────────────────────────────────

[20:22:21] ❗️ installer returned a non-zero exit code